### ISSUE TITLE
Update to latest version JQuery dependency

### ISSUE THREAD

**Issue by By-oussef** [AlexAltea/invoice#1]

**Comment by AlexAltea** [comment]
As of today, the latest version still seems to be jQuery 3.3.1 [[1]](https://jquery.com/download/), so this issue makes no sense at all.

Even if there was a more recent version: This repository is not affected by any known bugs, and any security patches applied to jQuery are completely irrelevant as the library is used to generate static sites that are printed to PDF locally.

[1] https://jquery.com/download/
